version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    container_name: second-brain-dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    ports:
      - "5000:5000"
      - "9229:9229" # Debug port
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=5000
    networks:
      - second-brain-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  second-brain-network:
    driver: bridge