version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://crm-dev:wkjoXL0B7aRGuq9z@free-cluster.pctfnoh.mongodb.net/crm-dev
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
      - NODE_ENV=development
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - DEBUG_ENCRYPTION=true # Enable encryption in development for testing
    networks:
      - mern-crm-network
    restart: unless-stopped
    # No need for MongoDB service since you're using MongoDB Atlas

networks:
  mern-crm-network:
    driver: bridge