[build]
  command = "yarn build"
  functions = "dist"
  publish = "dist"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200

[functions]
  node_bundler = "esbuild"
