import express from 'express';
import { auth, users, database } from '../modules';
import { workspaceRoutes } from '../modules/workspace';
import { filesRoutes } from '../modules/files';
import swaggerRoute from './swagger.route';
import categoryRoutes from '../modules/database/routes/database-category.routes';
import templatesRoutes from '../modules/database/routes/database-templates.routes';
import searchRoutes from '../modules/search/routes/search.routes';
import analyticsRoutes from '../modules/analytics/routes/analytics.routes';
import tagsRoutes from '../modules/tags/routes/tags.routes';
import notificationsRoutes from '../modules/notifications/routes/notifications.routes';
import taskDocumentViewRoutes from '../modules/second-brain/task/routes/task-document-view.routes';
import taskRoutes from '../modules/second-brain/task/routes/task.routes';
import noteRoutes from '../modules/second-brain/note/routes/note.routes';
import noteDocumentViewRoutes from '../modules/second-brain/note/routes/note-document-view.routes';
import projectRoutes from '../modules/second-brain/project/routes/project.routes';
import projectDocumentViewRoutes from '../modules/second-brain/project/routes/project-document-view.routes';
import goalDocumentViewRoutes from '../modules/second-brain/goal/routes/goal-document-view.routes';
import habitDocumentViewRoutes from '../modules/second-brain/habit/routes/habit-document-view.routes';
import bookDocumentViewRoutes from '../modules/second-brain/book/routes/book-document-view.routes';
import dashboardRoutes from '../modules/second-brain/dashboard/routes/dashboard.routes';
import databaseDocumentViewRoutes from '../modules/database/routes/database-document-view.routes';
import personDocumentViewRoutes from '../modules/second-brain/person/routes/person-document-view.routes';

const router = express.Router();

router.use('/docs', swaggerRoute);

router.use('/auth', auth.authRoutes);
router.use('/users', users.usersRoutes);
router.use('/workspaces', workspaceRoutes);
router.use('/databases', database.databaseRoutes);
router.use('/categories', categoryRoutes);
router.use('/templates', templatesRoutes);
router.use('/files', filesRoutes);
router.use('/search', searchRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/tags', tagsRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/second-brain/tasks', taskRoutes);
router.use('/second-brain/notes', noteRoutes);
router.use('/second-brain/projects', projectRoutes);
router.use('/second-brain', dashboardRoutes);
router.use('/document-views/tasks', taskDocumentViewRoutes);
router.use('/document-views/notes', noteDocumentViewRoutes);
router.use('/document-views/projects', projectDocumentViewRoutes);
router.use('/document-views/goals', goalDocumentViewRoutes);
router.use('/document-views/habits', habitDocumentViewRoutes);
router.use('/document-views/books', bookDocumentViewRoutes);
router.use('/document-views/databases', databaseDocumentViewRoutes);
router.use('/document-views/people', personDocumentViewRoutes);

export default router;