export enum EDatabaseType {
  DASHBOARD = 'dashboard',
  FINANCE = 'finance',
  GOALS = 'goals',
  JOURNAL = 'journal',
  MOOD_TRACKER = 'mood_tracker',
  NOTES = 'notes',
  TASKS = 'tasks',
  HABITS = 'habits',
  PEOPLE = 'people',
  // RESOURCES = 'resources',
  PARA_PROJECTS = 'para_projects',
  PARA_AREAS = 'para_areas',
  PARA_RESOURCES = 'para_resources',
  PARA_ARCHIVE = 'para_archive',
  // PROJECTS = 'projects',
  QUICK_TASKS = 'quick_tasks',
  QUICK_NOTES = 'quick_notes',
  CONTENT = 'content',
  ACTIVITY = 'activity',
  ANALYSIS = 'analysis',
  NOTIFICATIONS = 'notifications',

  CUSTOM = 'custom'
}
